---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME-$CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
spec:
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app: $CI_ENVIRONMENT_SLUG